# Generated by Django 6.0.3 on 2026-04-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(choices=[('Science', 'Science'), ('Business', 'Business'), ('Agriculture', 'Agriculture'), ('Home Economics', 'Home Economics'), ('Visual Arts', 'Visual Arts'), ('General Arts', 'General Arts')], max_length=30)),
                ('stream', models.CharField(max_length=1)),
                ('registration_year', models.PositiveSmallIntegerField(help_text='Full registration year, for example 2026.')),
                ('name', models.CharField(editable=False, max_length=50, unique=True)),
            ],
            options={
                'ordering': ['registration_year', 'programme', 'stream'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=30, unique=True)),
                ('programme', models.CharField(choices=[('Science', 'Science'), ('Business', 'Business'), ('Agriculture', 'Agriculture'), ('Home Economics', 'Home Economics'), ('Visual Arts', 'Visual Arts'), ('General Arts', 'General Arts')], default='Science', max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_admitted', models.DateField(blank=True, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['admission_number'],
            },
        ),
    ]
