# Generated by Django 6.0.3 on 2026-04-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Headteacher', 'Headteacher'), ('Assistant Headteacher Academic', 'Assistant Headteacher Academic'), ('Assistant Headteacher Domestic', 'Assistant Headteacher Domestic'), ('Assistant Headteacher Administration', 'Assistant Headteacher Administration'), ('Head of Department', 'Head of Department'), ('Senior House Teacher', 'Senior House Teacher'), ('House Teacher', 'House Teacher')], max_length=50),
        ),
    ]
