# Generated by Django 6.0.3 on 2026-04-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='title',
            field=models.CharField(choices=[('Headteacher', 'Headteacher'), ('Headteacher Academics', 'Headteacher Academics'), ('Headteacher Domestic', 'Headteacher Domestic'), ('Headteacher Administration', 'Headteacher Administration'), ('Dean of Discipline', 'Dean of Discipline'), ('Head of Department', 'Head of Department'), ('Senior House Teacher', 'Senior House Teacher'), ('House Teacher', 'House Teacher'), ('Form Teacher', 'Form Teacher')], max_length=120, unique=True),
        ),
    ]
